services:
  backend:
    build: apps/backend/
    container_name: backend
    ports:
      - "6769:6769"
    env_file: apps/backend/.env

  frontend:
    build: apps/frontend/
    container_name: frontend
    ports:
      - "42069:42069"
    depends_on:
      - backend
