{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  ZABBIX_URL: {{ .Values.secret.zabbixUrl | default "" | b64enc | quote }}
  ZABBIX_USER: {{ .Values.secret.zabbixUser | default "" | b64enc | quote }}
  ZABBIX_PASS: {{ .Values.secret.zabbixPass | default "" | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | default "" | b64enc | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | default "" | b64enc | quote }}
{{- end }}
