{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zabbix-portal-backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zabbix-portal-backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  ZABBIX_URL: {{ .Values.env.ZABBIX_URL | default "" | b64enc | quote }}
  ZABBIX_USER: {{ .Values.env.ZABBIX_USER | default "" | b64enc | quote }}
{{- end }}
